name: Main Workflow

on:
  push:
    branches:
      - master

jobs:
  call_echo_workflow_1:
    uses: ./.github/workflows/wf1.yml
    with:
      message: "Hello from Main Workflow!"
      number: 42

  # call_echo_workflow_2:
  #   runs-on: ubuntu-latest
  #   needs: call_echo_workflow_1
  #   uses: ./.github/workflows/wf2.yml  
  #   steps:
  #     - name: Call Echo Workflow 2
  #       uses: ./.github/workflows/wf2.yml  
  #       with:
  #         greeting: "Welcome"
  #         name: "User  "
  #         pass: ${{ secrets.pass }}  
  #   environment: app 