name: Echo Workflow 1

on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string
      number:
        required: true
        type: string
      service:
        required: false
        type: string

jobs:
  echo_job_1:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: ${{ inputs.service }}
        ports:
          - 27017:27017
    steps:
      - name: Echo Message
        run: |
          echo "Message from Workflow 1: ${{ inputs.message }}"
          echo "Number from Workflow 1: ${{ inputs.number }}"